Transaction controller
ManjunathBE/Ecommerce pull request #35
Opened 2020-09-08 18:11 UTC by gouthamcp

Transaction controller Implementation, Product and User Table Update,

2020-09-08 19:32 UTC, shariquemaaz commented on Backend/GroceryStore_Backend/Repository/IGroceryStoreRepository.cs
> +        Task<List<TransactionHistory>> GetTransactionHistories();
Consider renaming the method name as GetTransactionHistory

2020-09-08 19:48 UTC, shariquemaaz requested changes
1. consider renaming GetTransactionHistories to GetTransactionHistory
2. delete the obj folder in the root and then check in

2020-09-09 06:38 UTC, gouthamcp commented
> 1. consider renaming GetTransactionHistories to GetTransactionHistory
> 2. delete the obj folder in the root and then check in

Changes are updated

2020-09-09 06:57 UTC, shariquemaaz approved these changes

2020-09-09 09:11 UTC, merged